### ISSUE TITLE
torch.OutOfMemoryError

### ISSUE THREAD

**Issue by kth8** [Shadowfita/parakeet-tdt-0.6b-v2-fastapi#2]
I tried this wrapper and it works for short audio files but then when trying longer files it results in
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.49 GiB. GPU 0 has a total capacity of 7.91 GiB of which 909.25 MiB is free. Process 384269 has 31.63 MiB memory in use. Process 819532 has 28.77 MiB memory in use. Process 5582 has 7.77 MiB memory in use. Process 2068864 has 37.88 MiB memory in use. Process 2722258 has 50.96 MiB memory in use. Process 2760139 has 45.63 MiB memory in use. Process 3041402 has 169.39 MiB memory in use. Process 3043813 has 5.71 GiB memory in use. Of the allocated memory 5.36 GiB is allocated by PyTorch, and 218.56 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
could this be related to the lack of chunking that I also experienced when using on Mac? https://github.com/senstella/parakeet-mlx/issues/4

**Comment by Shadowfita** [comment]
Hi @kth8 ! It will definitely be related to a lack of chunking. I'll work to include chunking on the transcription endpoint. From what I've read, the model does have some native chunking support to a degree, so I'll see if I can leverage that firstly.

**Comment by Shadowfita** [comment]
@kth8 I've been able to transcribe a 1.25 hour youtube video in about 1.5 minutes (11k~ words, 3 minutes with timestamps) if letting the model handle chunking. Both VRAM and RAM usage increases dramatically however, so I think chunking in the wrapper will be the way to go.

**Comment by kth8** [comment]
@Shadowfita Transcribing long clips works now without crashing. I tested using a 1.5 hour podcast and it was able to finish in about 3 minutes. I see it using about 3.1GB of VRAM, lower than the 7GB you mentioned which I guess is good. It seems like most of that 3 minutes is spent in a "preprocessing" stage where no GPU is used but a single CPU core is pinned and the system RAM usage spike to over 9GB. ![nvtop](https://i.imgur.com/YYcCiIh.png)

**Comment by Shadowfita** [comment]
> [@Shadowfita](https://github.com/Shadowfita) Transcribing long clips works now without crashing. I tested using a 1.5 hour podcast and it was able to finish in about 3 minutes. I see it using about 3.1GB of VRAM, lower than the 7GB you mentioned which I guess is good. It seems like most of that 3 minutes is spent in a "preprocessing" stage where no GPU is used but a single CPU core is pinned and the system RAM usage spike to over 9GB. ![nvtop](https://camo.githubusercontent.com/0ac01e11c04cc9cd949336253eb44f5e9da37425e05bf47c703686cba3dc6794/68747470733a2f2f692e696d6775722e636f6d2f595963436949682e706e67)

That's likely the VAD step processing the audio for chunking. Definitely some things that I can do to improve the efficiency there. Great news about the VRAM though. 

There seems to be a decent delay in the file transfer itself through the fastapi library, and then the added delay of the VAD processing step. I'll need to improve these two things.

**Comment by Shadowfita** [comment]
@kth8 I've pushed another update which streams the file through the VAD step which has improved CPU and RAM usage. RAM usage drops considerably now but still has a larger initial spike on cold start and as the request is initiating. I'm hoping to improve this.

I've also attempted some garbage collection on the VRAM side of things. Cold start VRAM has improved considerably, and I now seem to be able to get under 2.2GB VRAM usage consistently while processing the 1.25 hour video. Takes about 70~ seconds without timestamps. Slight performance loss but big memory savings.

Let me know how it runs on your end.

**Comment by kth8** [comment]
I see VRAM usage decreased from 3.1GB to 2.3GB now while run time increased from 3 mins to ~3.5 mins. System RAM usage seems similar spiking to 8.5GB.

**Comment by Shadowfita** [comment]
> while running inference the system RAM usage is higher than before
> 
> ![nvtop](https://camo.githubusercontent.com/64b37e14853bc69ef8d5fc5601b237c87bd1a18217429922d5d2e953526ef77e/68747470733a2f2f692e696d6775722e636f6d2f4d4149627472682e706e67)

Hmm very interesting. For my large audio file, my system memory drops from \~8GB to \~3GB once inference starts. I'll keep investigating.

**Comment by kth8** [comment]
I see 4.6GB of system RAM just starting the server and spikes up to 13GB when processing a 3 hour stream.

![img](https://i.imgur.com/ZLLMViK.png)

**Comment by Shadowfita** [comment]
@kth8 Thanks for continuing to be available for testing.

I've pushed another update. Cold start memory usage shows roughly a 50% reduction on my system, and 75%+ while transcribing. VRAM usage is also sitting around ~2.1GB as well.

Hopefully this is the update that resolves it all!

**Comment by kth8** [comment]
Resource usage is much lower now :thumbsup:. I don't see any RAM usage spikes anymore and it stayed around 3.5-3.7GB throughout. VRAM usage was 1.4GB on start up and 2.5GB when doing inference.

![img](https://i.imgur.com/EY4iRg3.png)

**Comment by Shadowfita** [comment]
> Resource usage is much lower now 👍. I don't see any RAM usage spikes anymore and it stayed around 3.5-3.7GB throughout. VRAM usage was 1.4GB on start up and 2.5GB when doing inference.
> 
> ![img](https://camo.githubusercontent.com/54a7d794aa9343ddbd1d86672914bf826cb8073c1506e7bc32062f686b6dd7bc/68747470733a2f2f692e696d6775722e636f6d2f455934695267332e706e67)

Woo. Im going to consider this resolved now. Thanks so much for your help and testing every update, I really appreciate it.
